languange: python

sudo: false

services:
  - xvfb

addons:
  chrome: stable

install:
  - sudo apt update
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g puppeteer --unsafe-perm=true
  - sudo npm install -g @marp-team/marp-cli

script:
  - python3 compile_md.py --output _compiled.md lection/
  - marp --pdf _compiled.md
