language: python
services:
  - xvfb
addons:
  chrome: stable
install:
  - sudo apt update
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g puppeteer --unsafe-perm=true
  - sudo npm install -g @marp-team/marp-cli
script:
  - ./ci/git_merge_branches.sh
  - export TRAVIS_TAG=$TRAVIS_BRANCH-0.$TRAVIS_BUILD_NUMBER
  - python3 compile_md.py --output _compiled.md lection/
  - marp --pdf _compiled.md -o lection4-$TRAVIS_TAG.pdf
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export TRAVIS_TAG=$TRAVIS_BRANCH-0.$TRAVIS_BUILD_NUMBER
  - git tag $TRAVIS_TAG
deploy:
  cleanup: false
  provider: releases
  api_key: $GIT_TOKEN
  file: lection4-$TRAVIS_TAG.pdf
  on:
    repo: saysx-webservice/lection4_webservice
    tags: false
    branch: master

